openapi: 3.0.0
info:
  title: F1 Winner Prediction API
  version: 1.0.0
  description: API for predicting F1 race winners using machine learning
servers:
  - url: http://localhost:5000
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  model_loaded:
                    type: boolean
  /predict:
    post:
      summary: Predict race winner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drivers:
                  type: array
                  items:
                    type: object
                    properties:
                      driver_name:
                        type: string
                        description: Driver's full name
                      driver_win_rate:
                        type: number
                        description: Historical win rate for the driver
                      constructor_win_rate:
                        type: number
                        description: Historical win rate for the constructor
                      driver_season_points:
                        type: number
                        description: Cumulative points for the driver in current season
                      qualifying_position:
                        type: number
                        description: Position achieved in qualifying session
                      num_pit_stops:
                        type: number
                        description: Number of pit stops during the race
                      avg_pit_time:
                        type: number
                        description: Average pit stop time in milliseconds
                      total_pit_time:
                        type: number
                        description: Total pit stop time in milliseconds
                      grid:
                        type: number
                        description: Starting grid position
                      year:
                        type: number
                        description: Race year
                      driver_constructor_interaction:
                        type: number
                        description: Interaction term between driver and constructor win rates
                      grid_qualifying_diff:
                        type: number
                        description: Difference between grid and qualifying position
                      points_per_race:
                        type: number
                        description: Average points per race for the driver
                      recent_avg_position:
                        type: number
                        description: Average finishing position in recent races
                      constructor_recent_wins:
                        type: number
                        description: Number of recent wins for the constructor
                    required:
                      - driver_name
                      - driver_win_rate
                      - constructor_win_rate
                      - driver_season_points
                      - qualifying_position
                      - num_pit_stops
                      - avg_pit_time
                      - total_pit_time
                      - grid
                      - year
                      - driver_constructor_interaction
                      - grid_qualifying_diff
                      - points_per_race
                      - recent_avg_position
                      - constructor_recent_wins
              required:
                - drivers
      responses:
        '200':
          description: Prediction results
          content:
            application/json:
              schema:
                type: object
                properties:
                  predicted_winner:
                    type: object
                    properties:
                      driver_name:
                        type: string
                      win_probability:
                        type: number
                  all_predictions:
                    type: array
                    items:
                      type: object
                      properties:
                        driver_name:
                          type: string
                        win_probability:
                          type: number
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
