apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-api
  namespace: f1-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f1-api
  template:
    metadata:
      labels:
        app: f1-api
    spec:
      containers:
      - name: f1-api
        image: f1-winner-prediction:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9010
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9010
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9010
          initialDelaySeconds: 5
          periodSeconds: 5
