name: 🐛 Bug Report
description: Found a bug? Let me know!
title: "[BUG]: "
labels: ["bug"]
assignees:
  - rmidhun23

body:
  - type: textarea
    id: description
    attributes:
      label: What's broken?
      placeholder: Describe the bug and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      placeholder: |
        1. Step one
        2. Step two
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs (if any)
      render: shell
