name: ✨ Feature Request
description: Suggest an improvement
title: "[FEATURE]: "
labels: ["enhancement"]
assignees:
  - rmidhun23

body:
  - type: textarea
    id: problem
    attributes:
      label: What's missing?
      placeholder: Describe what you'd like to see added or improved
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Your idea
      placeholder: How would you solve this or what should it look like?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      placeholder: Any examples, references, or extra details
